### ISSUE TITLE
总是报路径不存在

### ISSUE THREAD

**Issue by ZTurboX** [xueyouluo/wiki-error-extract#1]
![image](https://user-images.githubusercontent.com/5669444/156083352-3b08ac52-efc3-442d-a37e-7ccaffd4f54c.png)

**Comment by xueyouluo** [comment]
是在解压那步就报错了吗？如果是的话建议先手动解压看看能否成功。 然后pipeline这边修改后，跑解压后面的流程看会不会报错

**Comment by ZTurboX** [comment]
> 是在解压那步就报错了吗？如果是的话建议先手动解压看看能否成功。 然后pipeline这边修改后，跑解压后面的流程看会不会报错

找到问题了，原始的脚本修改了一下，感觉有问题
![image](https://user-images.githubusercontent.com/5669444/156091959-6dc5416a-20f4-42fe-95a7-934389c1aac3.png)

**Comment by xueyouluo** [comment]
👍，目前这脚本效率挺低的，主要涉及了大量的读写小文件的操作，理论上可以把pipeline里面的操作都统一到一起，直接在内存操作

**Comment by ZTurboX** [comment]
> 👍，目前这脚本效率挺低的，主要涉及了大量的读写小文件的操作，理论上可以把pipeline里面的操作都统一到一起，直接在内存操作

之前做拼写纠错一直没有真实场景的数据，看到你的这个repo,想试试。

**Comment by ZTurboX** [comment]
> 👍，目前这脚本效率挺低的，主要涉及了大量的读写小文件的操作，理论上可以把pipeline里面的操作都统一到一起，直接在内存操作

你跑完数据花了多长时间呢

**Comment by zhentaoCoding** [comment]
> 👍，目前这脚本效率挺低的，主要涉及了大量的读写小文件的操作，理论上可以把pipeline里面的操作都统一到一起，直接在内存操作

你跑完数据花了多长时间呢

**Comment by xueyouluo** [comment]
> > 👍，目前这脚本效率挺低的，主要涉及了大量的读写小文件的操作，理论上可以把pipeline里面的操作都统一到一起，直接在内存操作
> 
> 你跑完数据花了多长时间呢

很久很久。。。放在机器上跑了N天。 我感觉可以把我跑出来的结果开源出来

**Comment by ZTurboX** [comment]
> > > 👍，目前这脚本效率挺低的，主要涉及了大量的读写小文件的操作，理论上可以把pipeline里面的操作都统一到一起，直接在内存操作
> > 
> > 
> > 你跑完数据花了多长时间呢
> 
> 很久很久。。。放在机器上跑了N天。 我感觉可以把我跑出来的结果开源出来

我说怎么一直没完。。

**Comment by xueyouluo** [comment]
> > > > 👍，目前这脚本效率挺低的，主要涉及了大量的读写小文件的操作，理论上可以把pipeline里面的操作都统一到一起，直接在内存操作
> > > 
> > > 
> > > 你跑完数据花了多长时间呢
> > 
> > 
> > 很久很久。。。放在机器上跑了N天。 我感觉可以把我跑出来的结果开源出来
> 
> 我说怎么一直没完。。

哈哈，主要是IO太慢了，其实改改放一起就好了，省去读写

**Comment by xueyouluo** [comment]
> 

更新了我的抽取结果，可以作为参考。
