### ISSUE TITLE
关于数据量

### ISSUE THREAD

**Issue by wangwang110** [xueyouluo/wiki-error-extract#4]
感觉提供代码，跑了很久，跑出来一份数据，数据量在100w+的样子。

但是我看有的报告里面，说提取将近600w+的拼写纠错数据。

请问您提取到的数据量大概是多少呢？

![image](https://user-images.githubusercontent.com/21475557/174271334-127a4f31-f0bd-4907-9fbc-01547f198761.png)

hsk，lang8两个数据集加起来不到30w

**Comment by xueyouluo** [comment]
不同的筛选方法得到的数量是不同的，比如我这里方法限制的比较严格，要求前后两个版本的文本的句子数量一样，而且只提取字数完全相同的pair，具体的可能跟他们的筛选方法相关了。我提取到的应该就是百万级别，具体多少我不记得了
